export const serviceChecklists: Record<string, string[]> = {
  'cleaning': [
    'Vacuumed all rooms',
    'Mopped hard floors',
    'Cleaned kitchen surfaces & appliances',
    'Cleaned bathroom (toilet, sink, shower)',
    'Dusted all surfaces & shelves',
    'Cleaned mirrors & glass',
    'Emptied all bins',
    'Made beds (if requested)',
    'Wiped switches & door handles',
    'Final walkthrough complete',
  ],
  'ac-services': [
    'Checked and cleaned filters',
    'Cleaned evaporator coil',
    'Cleaned condenser coil',
    'Checked drainage pipe',
    'Tested cooling output',
    'Checked thermostat calibration',
    'Inspected electrical connections',
    'Checked refrigerant level',
    'Cleaned external unit',
    'Final test — all units cooling properly',
  ],
  'pest-control': [
    'Inspected kitchen & food storage areas',
    'Inspected bathrooms & wet areas',
    'Checked entry points (windows, doors, pipes)',
    'Applied treatment to identified areas',
    'Set bait stations (if applicable)',
    'Treated baseboards & crevices',
    'Applied gel bait in kitchen (if cockroach)',
    'Checked for signs of nesting',
    'Provided post-treatment safety instructions',
    'Scheduled follow-up (if required)',
  ],
  'plumbing': [
    'Inspected reported issue',
    'Shut off water supply (if needed)',
    'Completed repair/installation',
    'Tested for leaks',
    'Checked water pressure',
    'Cleaned work area',
    'Tested all affected fixtures',
    'Provided maintenance advice',
  ],
  'electrical': [
    'Inspected reported issue',
    'Switched off power at breaker',
    'Completed repair/installation',
    'Tested circuit with multimeter',
    'Checked all connections secure',
    'Restored power and tested',
    'Cleaned work area',
    'Provided safety recommendations',
  ],
  'painting': [
    'Covered furniture & floors with drop cloths',
    'Filled holes & cracks with filler',
    'Sanded surfaces smooth',
    'Applied painter tape to edges',
    'Applied primer coat',
    'Applied first paint coat',
    'Applied second paint coat (if needed)',
    'Removed tape before final dry',
    'Cleaned all equipment & area',
    'Final touch-up inspection',
  ],
};
